theme = "nxyt"

[editor]
line-number = "relative"
auto-format = true
auto-save = true
true-color = true
bufferline = "always"
idle-timeout = 40
color-modes = true
text-width = 90

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
max-depth = 14


[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 3

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
X = "extend_line_above"
C-space = "completion"
V = ["select_mode", "extend_to_line_bounds"]
S-left = ":bprev"
S-right = ":bnext"
C-j = "half_page_down"
C-k = "half_page_up"

space = { q = { a = ":pipe echo elo" } }

[keys.insert]
C-space = "completion"
